version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django-app
    ports:
      - 8000:8000
    image: django01draft_img:1.0
    container_name: django01draft_container
    command: python manage.py runserver 0.0.0.0:8000